name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: tello_driver, tello_msgs, tello_description, tello_gazebo
          target-ros2-distro: foxy
